language: android
android:
  components:
  - tools
  - build-tools-27.0.3
  # The SDK version used to compile your project
  - android-27
  - android-22
  # Additional components
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository

script:
  - "chmod +x ./gradlew"
  - "./gradlew assembleRelease"